---
title: "ads_project"
author: "Benjamin S. Wynia"
date: "September 14, 2017"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
properties <- read.csv("properties_2016.csv")
```

```{r}
# I can't remember which libraries I want, so here's a bunch of random ones
library(zoo)
library(plyr)
library(MASS)
library(leaps)
library(stringr)
library(stats)
library(ggplot2)
library(gplots)
library(e1071)
library(stringr)
library(FNN)

```


```{r}
# Create sets for each county
county1 <- subset(properties, properties$regionidcounty == 1286)
county2 <- subset(properties, properties$regionidcounty == 2061)
county3 <- subset(properties, properties$regionidcounty == 3101)
```
## Data Summary

##### County 1
```{r}
# Number of records 
NROW(county1$taxvaluedollarcnt)

# Descriptive statistics
summary(county1$taxvaluedollarcnt)

# Binned ranges 
table(cut(county1$taxvaluedollarcnt, breaks=c(100000, 200000, 300000, 450000, 750000, 1000000, 5000000), labels=c("< 100000", "200,000", "300,000", "450,000", "750000", "> 1,000,000")))
```
##### County 2
```{r}
# Number of records 
NROW(county2$taxvaluedollarcnt)

# Descriptive statistics
summary(county2$taxvaluedollarcnt)

# Binned ranges 
table(cut(county2$taxvaluedollarcnt, breaks=c(100000, 200000, 300000, 450000, 750000, 1000000, 5000000), labels=c("< 100000", "200,000", "300,000", "450,000", "750000", "> 1,000,000")))
```

##### County 3
```{r}
# Number of records 
NROW(county3$taxvaluedollarcnt)

# Descriptive statistics
summary(county3$taxvaluedollarcnt)

# Binned ranges 
table(cut(county3$taxvaluedollarcnt, breaks=c(100000, 200000, 300000, 450000, 750000, 1000000, 5000000), labels=c("< 100000", "200,000", "300,000", "450,000", "750000", "> 1,000,000")))

```

## Simple Linear Model
```{r}
# County 1
fit <- lm(county1$taxvaluedollarcnt ~ county1$bedroomcnt + county1$bathroomcnt, data = county1)
summary(fit)

# County 2
fit <- lm(county2$taxvaluedollarcnt ~ county2$bedroomcnt + county2$bathroomcnt, data = county2)
summary(fit)

# County 3
fit <- lm(county3$taxvaluedollarcnt ~ county3$bedroomcnt + county3$bathroomcnt, data = county3)
summary(fit)

```

## Load dependent variable dataset
```{r}
# Two data sets. "Properties" has all the independent variables. "Train_logerror" has our dependent variable.
# Merge data sets using "parcelid"

train_logerror <- read.csv("train_logerror.csv")
houses_merged <- merge(properties,train_logerror,by="parcelid")

```

## Set the variable types in R
```{r}
# Determine current type of all variables
sapply(houses_merged,class)

```

```{r}
# Define Categorical Variables

# Type of Ait Conditioning-  Type of cooling system present in the home (if any)
houses_merged$airconditioningtypeid <- factor(houses_merged$airconditioningtypeid,
                                              levels=c(1,2,3,4,5,6,7,8,9,10,11,12,13),
                                              labels=c("Central","Chilled Water","Evaporative Cooler","Geo Thermal","None","Other","Packaged AC Unit","Partial","Refrigeration","Ventilation","Wall Unit","Window Unit","Yes"))

houses_merged$heatingorsystemtypeid <- factor(houses_merged$heatingorsystemtypeid,
                                              levels=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25),
                                              labels=c("Baseboard","Central","Coal","Convection","Electric","Forced air","Floor/Wall","Gas","Geo Thermal","Gravity","Heat Pump","Hot Water","None","Other","Oil","Partial","Propane","Radiant","Steam","Solar","Space/Suspended","Vent","Wood Burning","Yes","Zone"))


houses_merged$propertylandusetypeid<- factor(houses_merged$propertylandusetypeid,                                      levels=c(31,46,47,246,247,248,260,261,262,263,264,265,266,267,268,269,270,271,273,274,275,276,279,290,291),
labels=c("Commercial/Office/Residential Mixed Used","Multi-Story Store","Store/Office (Mixed Use)","Duplex (2 Units, Any Combination)","Triplex (3 Units, Any Combination)","Quadruplex (4 Units, Any Combination)","Residential General","
Single Family Residential","Rural Residence","Mobile Home","Townhouse","Cluster Home","Condominium","Cooperative","Row House","
Planned Unit Development","Residential Common Area","Timeshare","Bungalow","Zero Lot Line","Manufactured, Modular, Prefabricated Homes","Patio Home","Inferred Single Family Residential","Vacant Land - General","Residential Vacant Land"))


houses_merged$storytypeid <- factor(houses_merged$storytypeid,                                 levels=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35),
labels=c("Attic & Basement","Attic","Bi-Level with Attic & Basement","Bi-Level","Bi-Level with Attic","Bi-Level with Basement","Basement","Split Entry with Attic & Basement","Split Foyer with Attic & Basement","Level with Attic & Basement","Level with Attic","Level with Basement","Level","Multi-Level with Attic & Basement","Multi-Level","Multi-Level with Attic","Multi-Level with Basement","Split Level with Attic & Basement","Single Level with Attic & Basement","Split Entry with Attic"," Split Entry with Basement","Split Foyer with Attic","Split Foyer with Basement","Single Level with Attic","Single Level with Basement","Single Level","Split Level with Attic","Split Level with Basement","Split Entry","Split Foyer","Split Level","Tri-level with Attic & Basement","Tri-level with Attic","Tri-level with Basement","Tri-level"))

houses_merged$architecturalstyletypeid<- factor(houses_merged$architecturalstyletypeid,                                 levels=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27),
labels=c("A-Frame","Bungalow","Cape Cod","Cottage","Colonial","Custom","Contemporary","Conventional","Dome","French Provincial","Georgian","High Rise","Historical","Log Cabin/Rustic","Mediterranean","Modern","Mansion","English","Other","Prefab","Ranch/Rambler","Raised Ranch","Spanish","Traditional","Tudor","Unfinished/Under Construction","Victorian"))

houses_merged$typeconstructiontypeid<- factor(houses_merged$typeconstructiontypeid,                                 levels=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18),
labels=c("Adobe","Brick","Concrete Block","Concrete","Dome","Frame","Heavy","Log","Light","Metal","Manufactured","Mixed","Masonry","Other","Steel","Stone","Tilt-Up","Wood"))

# See Data Dictionary
houses_merged$buildingclasstypeid<- factor(houses_merged$buildingclasstypeid,                                 levels=c(1,2,3,4,5),
labels=c("Type 1","Type 2","Type 3","Type 4","Type 5"))

```

```{r}
# Define Longitude and Latitude as Numeric
houses_merged$longitude <- as.numeric(houses_merged$longitude)
houses_merged$latitude <- as.numeric(houses_merged$latitude)

# Define deck type ID as categorical
houses_merged$decktypeid <- as.factor(houses_merged$decktypeid)

# Define buildingqualitytypeid as factor
houses_merged$buildingqualitytypeid <- as.factor(houses_merged$buildingqualitytypeid)

# Define fips as categorical-- we may want to come back and do something with this later with respect to geocoding
houses_merged$fips <- as.factor(houses_merged$fips)

# pool variables as factor 
houses_merged$pooltypeid10 <-as.factor(houses_merged$pooltypeid10)
houses_merged$pooltypeid2 <-as.factor(houses_merged$pooltypeid2)
houses_merged$pooltypeid7 <- as.factor(houses_merged$pooltypeid7)

# census tract and block as factor- may use for geocoding later or grouping as a "neighborhood" variable
houses_merged$rawcensustractandblock <- as.factor(houses_merged$rawcensustractandblock)
houses_merged$censustractandblock <- as.factor(houses_merged$censustractandblock)

# other geographic variables
houses_merged$regionidcity <-as.factor(houses_merged$regionidcity)
houses_merged$regionidcounty <- as.factor(houses_merged$regionidcounty)
houses_merged$regionidneighborhood <- as.factor(houses_merged$regionidneighborhood)
houses_merged$regionidzip <- as.factor(houses_merged$regionidzip)

houses_merged$yardbuildingsqft17 <-as.factor(houses_merged$yardbuildingsqft17)
houses_merged$yardbuildingsqft26 <-as.factor(houses_merged$yardbuildingsqft26)

# date variable
houses_merged$transactiondate <- as.Date(houses_merged$transactiondate)

practice_set[,46]<- as.numeric(practice_set[,46])

```

```{r}
# Review type of all variables
sapply(houses_merged,class)

```

## Create new dataset with dependent variable
```{r}
# Creating a new dataset which only includes properties with a known "logerror"
nrow(train_logerror)
home_data <- houses_merged[is.na(houses_merged$logerror)==FALSE,]
nrow(home_data)

# Creating a reasonable subset for testing simple models
practice_set <- home_data


```


## Linear model of logerror=log(Zestimate)-log(Actual Price) as a function of independent variables
```{r}
# Which numeric variable does the best job of explaining the variation between Zestimate and Price (logerror)?
r_squared <- as.vector(rep(0,ncol(home_data)))
name_vector <- as.vector(rep(NA,ncol(home_data)))

# Create a vector with all the variable names
for (i in 1:ncol(home_data)) {
  name_vector[i]<- colnames(home_data[i])
}

# Run the linear model for all variables, record adjusted r^2
# did this one by one instead of in a loop because several of the variables only have one level or 1000's of levels
# I will probably clean this up later and create a separate dataset to use for all the linear models
r_squared[2] <- summary(lm(logerror ~ home_data[,2],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[3] <- summary(lm(logerror ~ home_data[,2],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[4] <- summary(lm(logerror ~ home_data[,4],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[5] <- summary(lm(logerror ~ home_data[,5],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[6] <- summary(lm(logerror ~ home_data[,6],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[9] <- summary(lm(logerror ~ home_data[,9],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[8] <- summary(lm(logerror ~ home_data[,8],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[11] <- summary(lm(logerror ~ home_data[,11],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[12] <- summary(lm(logerror ~ home_data[,12],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[13] <- summary(lm(logerror ~ home_data[,13],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[14] <- summary(lm(logerror ~ home_data[,14],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[15] <- summary(lm(logerror ~ home_data[,15],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[16] <- summary(lm(logerror ~ home_data[,16],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[17] <- summary(lm(logerror ~ home_data[,17],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[19] <- summary(lm(logerror ~ home_data[,19],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[20] <- summary(lm(logerror ~ home_data[,20],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[21] <- summary(lm(logerror ~ home_data[,21],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[22] <- summary(lm(logerror ~ home_data[,22],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[23] <- summary(lm(logerror ~ home_data[,23],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[24] <- summary(lm(logerror ~ home_data[,24],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[25] <- summary(lm(logerror ~ home_data[,25],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[26] <- summary(lm(logerror ~ home_data[,26],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[27] <- summary(lm(logerror ~ home_data[,27],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[28] <- summary(lm(logerror ~ home_data[,28],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[29] <- summary(lm(logerror ~ home_data[,29],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[33] <- summary(lm(logerror ~ home_data[,33],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[34] <- summary(lm(logerror ~ home_data[,34],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[37] <- summary(lm(logerror ~ home_data[,37],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[38] <- summary(lm(logerror ~ home_data[,38],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[39] <- summary(lm(logerror ~ home_data[,39],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[40] <- summary(lm(logerror ~ home_data[,40],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[41] <- summary(lm(logerror ~ home_data[,41],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[43] <- summary(lm(logerror ~ home_data[,43],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[45] <- summary(lm(logerror ~ home_data[,45],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[46] <- summary(lm(logerror ~ home_data[,46],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[48] <- summary(lm(logerror ~ home_data[,48],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[49] <- summary(lm(logerror ~ home_data[,49],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[50] <- summary(lm(logerror ~ home_data[,50],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[51] <- summary(lm(logerror ~ home_data[,51],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[52] <- summary(lm(logerror ~ home_data[,52],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[53] <- summary(lm(logerror ~ home_data[,53],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[54] <- summary(lm(logerror ~ home_data[,54],na.action=na.exclude, data = home_data))$adj.r.squared
r_squared[55] <- summary(lm(logerror ~ home_data[,55],na.action=na.exclude, data = home_data))$adj.r.squared

# Write resulting variables and adjusted r^2 to data frame
sig_frame <- data.frame(name_vector,r_squared)

# order data frame from most to least significant
sig_frame <- sig_frame[order(-r_squared),]
colnames(sig_frame) <- c("Variable Name","Adj. R^2")

# Print 10 most significant variables
sig_frame[1:15,]

# Basement size may explain up to 4% of the variation in the log error. 

```

## Nearest Neighbors Model
```{r}



```

## Backwise Search Model
```{r}
# THE NA values are making this break
#backwise_model <- lm(logerror ~ basementsqft + propertycountylandusecode + finishedsquarefeet12 + calculatedfinishedsquarefeet +  threequarterbathnbr + fireplacecnt + calculatedbathnbr + fullbathcnt + bathroomcnt + garagecarcnt + bedroomcnt,na.action=na.exclude, data = home_data)
#backwise_step <- stepAIC(backwise_model, direction = "backward", trace = FALSE)
#backwise_step$anova
#summary(backwise_step)



```

```{r}




```

```{r}




```

```{r}




```


